define({
    rota: {
        menuler: 'Menüler',
        devreyealimuyarisi: '{0} dk içinde bakım başlıyacaktır.Lütfen işinizi sonlandırıp uygulamadan çıkınız',
        kullanmayadevamet: 'Kullanmaya devam et',
        bostacalismabaslik: 'Boşta çalışma kontrolü',
        bostacalismauyarisi: 'Herhangi bir işlem yapmadığınız için uygulama {0} içinde kapatılacak',
        okumamoduuyari: 'Bu sayfa okuma amaçlıdır,değişiklik yapamazsınız !',
        sadeceokuma: 'Sadece okuma',
        hepsinisec: 'Hepsini seç',
        secimlerikaldir: 'Seçimleri kaldır',
        hepsiniac: 'Hepsini aç',
        hepsinikapat: 'Hepsini kapat',
        escsilaciklama: 'Temizlemek için <b>\'esc\'</b> e basınız',
        enazkaraktersayisi: 'En az <b>\'{0}\'</b> karakter girmelisiniz',
        yeniitemicinarti: 'Yeni item eklemek için <b>\'+\'</b> ya basınız',
        otomatikkayit: 'Otomatik kayıt onay',
        otomatikkayityuklensinmi: 'Bu form bilinmeyen bir şekilde kapandı,form bilgisini tekrar yüklemek istiyormusunuz ?',
        otomatikkayityukle: 'Otomatik kayıtlı datayı yükle',
        otomatikkayitediliyor: 'Otomatik kayıt ediliyor...',
        degisikliklergerialindi: 'Yapilan değişiklikler geri alındı',
        silinenitemgerialindi: 'Silinen kayıt geri alındı',
        aktifsirket: 'Aktif Şirket',
        indirpdf: 'Pdf olarak',
        indirxls: 'Excel olarak',
        indirword: 'Word olarak',
        indirhtml: 'Html olarak',
        indir: 'İndir',
        goster: 'Göster',
        raporgoster: 'Raporu Göster',
        raporukapat: 'Raporu kapat',
        raporonizleme: 'Rapor önizleme',
        buguntarihienter: 'Bugünün tarihi için enter\'a basınız',
        islemler: 'İşlemler',
        dosyaekleaciklama: 'Sürekle bırak veya linke tıklayarak yeni dosya ekleyin',
        yenidosyaekle: 'Yeni dosya ekle',
        tumdataexportonay: 'Tüm kayıtları export etmek zaman alabilir.Devam etmek istiyormusunuz ?',
        ilkkaydagit: 'İlk kayda git',
        kirptitle: 'Kırpılacak alanı seçiniz',
        kirp: 'Kırp',
        fotodegistirildi: 'Fotoğraf değiştirildi',
        fotodegistir: 'Fotoğrafımı değiştir',
        fotosec: 'Avatar resmi seçiniz...',
        fotodegistirhata: 'Avatar resmi değiştirilemedi !',
        yardim: 'Yardım',
        kisayollar: 'Kısayollar',
        diller: 'Diller',
        sirketler: 'Şirketler',
        hizlimenuekle: 'Hızlı menü ekle',
        hizlimenusilmehatasi: 'Bu menü kaldırılamaz',
        hizliemenuadetkisiti: 'Max {0} adet hizli menu ekleyebilirsiniz',
        createduser: 'Yaratan Kull.',
        createddate: 'Yaratma Tarihi',
        modifieduser: 'Güncelleyen Kull.',
        modifieddate: 'Güncelleme Tarihi',
        urlparametrebilgi: "Url parametrelerine varsayilan deger atamak için '{parametren}' şeklinde tanımlama yapabilirsiniz.Örn:Deneme/:id{1}",
        duzeltiliyor: 'Düzeltiliyor',
        zorunlualanlarvar: 'Eksik alanları doldurunuz',
        evet: 'Evet',
        hayir: 'Hayır',
        kopyalaniyor: 'Kopyalanıyor',
        disariyaaktar: 'Dışarıya Aktar',
        aktarallcsv: 'Tüm data .csv',
        aktarekrandakicsv: 'Ekrandaki data .csv',
        aktarsecilicsv: 'Seçili data .csv',
        aktarallpdf: 'Tüm data .pdf',
        aktarekrandakipdf: 'Ekrandaki data .pdf',
        aktarsecilipdf: 'Seçili data .pdf',
        sayfa: 'Sayfa',
        toplam: 'Toplam',
        son: 'Son',
        ilk: 'İlk',
        yeni: 'Yeni',
        yenikopyala: 'Kaydı kopyala',
        kayitkopyalandı: 'Kayıt başarıyla kopyalandı',
        bilinmeyenhataolustu: 'Bilinmeyen hata oluştu',
        sonrakikayit: 'Sonraki',
        oncekikayit: 'Önceki',
        yenikayit: 'Yeni kayıt',
        kayitduzeltme: 'Düzeltme',
        kayitbasarisiz: 'Kayıt işlemi iptal edildi',
        ara: 'Ara',
        temizle: 'Temizle',
        crudonay: 'Yaptıgınız değişiklikleri kayit etmek istiyormusunuz ?',
        tt_yenikayit: 'Yeni kayıt açar',
        tt_bironcekisayfayadon: 'Bir önceki sayfaya gider',
        tt_kaydet: 'Yapılan değişiklikleri kayıt eder',
        tt_kaydetdevam: 'Değişklikleri kaydedip yeni kayıt açar',
        tt_gerial: 'Yapılan değişiklikleri geri alır',
        tt_sil: 'Kaydı siler',
        gonder: 'Gönder',
        tt_dosyasecmekicintiklayiniz: 'Dosya seçmek için tıklayınız',
        dosyaseciniz: 'Dosya seçiniz...',
        yenidosya: 'Yeni dosya',
        fileuploaded: 'Dosya başarıyla yüklendi',
        iptal: 'İptal',
        bugun: 'Bugün',
        sonbirhafta: 'Son 1 hafta',
        sonbiray: 'Son 1 ay',
        sonaltiay: 'Son 6 ay',
        sonbiryil: 'Son 1 yil',
        ozel: 'Özel',
        cikisonay: 'Çıkmak istediğinize eminmisiniz ?',
        cikisyapiliyor: 'Çıkış yapılıyor...',
        filter: 'Filtre Kriterleri',
        ayarlar: 'Ayarlar',
        genislet: 'Genişlet',
        daralt: 'Daralt',
        filtreyitemizle: 'Filtreyi temizle',
        kayitsilindi: 'Kayıt silindi',
        kayiteklendi: 'Kayıt eklendi',
        tumkayitlarsilindi: 'Tüm kayıtlar silindi',
        tumkayitlareklendi: 'Tüm kayıtlar eklendi',
        zatenekli: 'Kayıt zaten ekli !',
        onay: 'Onay',
        onaytumkayitekle: 'Tüm kayıtlar eklenecek devam etmek istiyormusunuz ?',
        onaytumkayitsil: 'Tüm kayıtlar silinecek devam etmek istiyormusunuz ?',
        tumunuekle: 'Tüm kayıtları ekle',
        tumunusil: 'Tüm kayıtları sil',
        secilikayitlarisil: 'Seçili kayıtları sil',
        onaysecilikayitlarisil: 'Seçili kayıtlar silinecek devam etmek istiyormusunuz ?',
        kayitsayisi: 'Kayit sayısı',
        kayitbulunamadi: 'Kayıt bulunamadı',
        close: "Kapat",
        prev: 'Önceki',
        next: 'Sonraki',
        first: 'İlk',
        last: 'Son',
        kaydetdevam: 'Kaydet & Devam',
        succesfullyprocessed: 'İşlem başarıyla tamamlanmıştır!',
        titleinfo: 'Bilgi',
        titleerror: 'Hata',
        titlewarn: 'Uyarı',
        titlesuccess: 'Başarılı',
        titledebug: 'Debug',
        seciniz: "Seçim Yapınız..",
        zorunlualan: 'Bu alan zorunludur',
        maxuzunluk: 'En fazla {0} karakter girebilirsiniz',
        minuzunluk: 'En az {0} karakter girmelisiniz',
        hatalimail: 'Geçerli email adresi girmelisiniz',
        hataliurl: 'Geçerli url girmelisiniz',
        hatalisayi: 'Geçerli sayı girmelisiniz',
        hatalipattern: 'Girdiğiniz değer pattern\'e uymuyor',
        hatalitariharaligimin: '{0}\'den sonraki bir tarih seçmelisiniz',
        hatalitariharaligimax: '{0}\'den önceki bir tarih seçmelisiniz',
        hatalidegermin: 'Girdiğiniz sayı {0}\'dan büyük olmalı',
        hatalidegermax: 'Girdiğiniz sayı {0}\'dan küçük olmalı',
        yenile: "Yenile",
        geridon: "Bir önceki sayfaya dön",
        sil: "Sil",
        Detay: "Detay",
        tamam: 'Tamam',
        ekle: "Ekle",
        guncelle: "Güncelle",
        kaydet: "Kaydet",
        gerial: "Geri Al",
        ok: "Tamam",
        deleteconfirmtitle: "Silme Onayı",
        deleteconfirm: "Kaydı silmek istediğinize eminmisiniz ?",
        unauthorized: "Bu formu görmeye yetkiniz yok !",
        invalidfiletypemessage: "Sadece {0} uzantılı dosyaları yükleyebilirsiniz.<b><i>{1}</i></b> dosyasının yüklemesi iptal oldu !",
        lutfenbekleyiniz: "Lütfen bekleyiniz...",
        durum: "Durum",
        sayfabulunamadi: "Sayfa Bulunamadı",
        error404description: "Aradığınız sayfa bulunamadı,sistem yöneticisi ile görüşün veya tekrar deneyin.Browserin geri tuşunu kullanarak bir önceki sayfaya dönebilirsiniz.",
        aktifmi: "Aktif mi?",
        yetkihatasiaciklama: "Bu işlemi yapmaya yetkiniz yok!",
        yetkihatasi: "Yetki Hatası",
        validationhatasi: "Eksik & Hatalı Alan !",
        hata: 'Hata',
        yenidenbaslat: 'Yeniden başlat !',
        hataolustu: 'Uygulamada hata oluştu !',
        hataozur: 'Oluşan hata yüzünden özür dileriz,hata ile ilgili bilgiler sistemimize kayit edildi.En yakın zamanda sorunu çözeceğiz.',
        hataaciklama: 'Hata detayi :',
        secilikayit: 'Seçili {0}',
        modelbulunamadi: 'Aradığınız kayıt silinmiş veya görme yetkiniz yok.<b>\'Yeni kayıt\'</b> moduna geçildi!',
        logout: 'Çıkış'
    }
});